// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using leiloFlash_backend.Data;

#nullable disable

namespace leiloFlash_backend.Migrations
{
    [DbContext(typeof(LeiloDbContext))]
    partial class LeiloDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("leiloFlash_backend.Models.EnderecoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("complemento");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("logradouro");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("numero");

                    b.HasKey("Id");

                    b.ToTable("Endereco", (string)null);
                });

            modelBuilder.Entity("leiloFlash_backend.Models.ImagemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_upload");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("url");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("int")
                        .HasColumnName("veiculo_id");

                    b.HasKey("Id");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Imagem", (string)null);
                });

            modelBuilder.Entity("leiloFlash_backend.Models.LanceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_hora");

                    b.Property<int?>("LoteId")
                        .HasColumnType("int")
                        .HasColumnName("lote_id");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Lance", (string)null);
                });

            modelBuilder.Entity("leiloFlash_backend.Models.LeilaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_inicio");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.Property<string>("StatusLeilao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status_leilao");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Leilao", (string)null);
                });

            modelBuilder.Entity("leiloFlash_backend.Models.LoteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("LeilaoId")
                        .HasColumnType("int")
                        .HasColumnName("leilao_id");

                    b.Property<int>("NumeroLote")
                        .HasColumnType("int")
                        .HasColumnName("numero_lote");

                    b.Property<int?>("UltimoLanceUsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("ultimo_lance_usuario_id");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.Property<decimal?>("ValorAtual")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_atual");

                    b.Property<decimal?>("ValorFinal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_final");

                    b.Property<decimal>("ValorInicial")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_inicial");

                    b.Property<int?>("VeiculoId")
                        .HasColumnType("int")
                        .HasColumnName("veiculo_id");

                    b.HasKey("Id");

                    b.HasIndex("LeilaoId");

                    b.HasIndex("UltimoLanceUsuarioId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Lote", (string)null);
                });

            modelBuilder.Entity("leiloFlash_backend.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<int?>("EnderecoId")
                        .HasColumnType("int")
                        .HasColumnName("endereco_id");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("senha");

                    b.Property<string>("StatusUsuario")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status_usuario");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("telefone");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId")
                        .IsUnique()
                        .HasFilter("[endereco_id] IS NOT NULL");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("leiloFlash_backend.Models.VeiculoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("ano");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cor");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("modelo");

                    b.Property<decimal>("ValorInicial")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_inicial");

                    b.Property<decimal>("kmAtual")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("km_atual");

                    b.HasKey("Id");

                    b.ToTable("Veiculo", (string)null);
                });

            modelBuilder.Entity("leiloFlash_backend.Models.ImagemModel", b =>
                {
                    b.HasOne("leiloFlash_backend.Models.VeiculoModel", "Veiculo")
                        .WithMany("Imagens")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("leiloFlash_backend.Models.LanceModel", b =>
                {
                    b.HasOne("leiloFlash_backend.Models.LoteModel", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId");

                    b.HasOne("leiloFlash_backend.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Lote");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("leiloFlash_backend.Models.LeilaoModel", b =>
                {
                    b.HasOne("leiloFlash_backend.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("leiloFlash_backend.Models.LoteModel", b =>
                {
                    b.HasOne("leiloFlash_backend.Models.LeilaoModel", "Leilao")
                        .WithMany("Lotes")
                        .HasForeignKey("LeilaoId");

                    b.HasOne("leiloFlash_backend.Models.UsuarioModel", "UltimoLanceUsuario")
                        .WithMany()
                        .HasForeignKey("UltimoLanceUsuarioId");

                    b.HasOne("leiloFlash_backend.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.HasOne("leiloFlash_backend.Models.VeiculoModel", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId");

                    b.Navigation("Leilao");

                    b.Navigation("UltimoLanceUsuario");

                    b.Navigation("Usuario");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("leiloFlash_backend.Models.UsuarioModel", b =>
                {
                    b.HasOne("leiloFlash_backend.Models.EnderecoModel", "Endereco")
                        .WithOne("Usuario")
                        .HasForeignKey("leiloFlash_backend.Models.UsuarioModel", "EnderecoId");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("leiloFlash_backend.Models.EnderecoModel", b =>
                {
                    b.Navigation("Usuario")
                        .IsRequired();
                });

            modelBuilder.Entity("leiloFlash_backend.Models.LeilaoModel", b =>
                {
                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("leiloFlash_backend.Models.VeiculoModel", b =>
                {
                    b.Navigation("Imagens");
                });
#pragma warning restore 612, 618
        }
    }
}
